apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ include "busybeaver.fullname" . }}--cron--queue-upcoming-events"
  labels:
    type: post-upcoming-events
    {{- include "busybeaver.labels" . | nindent 4 }}
spec:
  schedule: "0 14 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: busybeaver--queue-upcoming-events-jobs
            image: {{ .Values.image.repository }}:{{ .Values.image.version }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["flask"]
            args:
            - "queue_post_upcoming_events_jobs"
            env: {{- include "busybeaver.env_vars" . | indent 12 }}
